// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HealthRecords$Type } from "./HealthRecords";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HealthRecords"]: HealthRecords$Type;
    ["contracts/contracts/HealthRecords.sol:HealthRecords"]: HealthRecords$Type;
  }

  interface ContractTypesMap {
    ["HealthRecords"]: GetContractReturnType<HealthRecords$Type["abi"]>;
    ["contracts/contracts/HealthRecords.sol:HealthRecords"]: GetContractReturnType<HealthRecords$Type["abi"]>;
  }
}
